// uni-vite/src/pages/me/index.vue
<template>
  <view>
    <view class="me_page">
      <view v-if="userInfo" class="user_info">
        <view class="avatar">
          <image class="image" :src="replaceCosDomainName(defaultAvatar)" mode="aspectFill" />
        </view>
        <view class="user_detail">
          <view class="user_name">
            <text class="name">
              {{ userInfo.nickname || userInfo.name }}
            </text>
            <text class="role">
              {{ getRoleLabel(userInfo.role)}}
            </text>
          </view>
          <view class="user_phone">
            <a class="phone" :href="`tel:${userInfo.phone_number}`">
              {{ userInfo.phone_number }}
            </a>
          </view>
        </view>
      </view>
      <view v-else class="login">
        <view class="button" @click="gotoLogin">
          登录
        </view>
      </view>
      <view class="main">
        <view class="features">					
          <view
            v-for="item in featureOptions"
            :key="item.name"
            class="item"
            @click="openUrl(item)"
          >
            <view>{{ item.name }}</view>
            <uni-icons type="right" size="18" color="#ccc"></uni-icons>
          </view>
        </view>

        <view class="features">					
          <view
            v-for="item in baseOptions"
            :key="item.key"
            class="item"
            @click="onClickOther(item)"
          >
            <view>{{ item.name }}</view>
            <uni-icons type="right" size="18" color="#ccc"></uni-icons>
          </view>
        </view>
      </view>
      <view v-if="userInfo" class="logout">
        <text class="text" @click="onChangePassword">修改密码</text>
        |
        <text class="text" @click="onLogout">退出登录</text>
      </view>
    </view>
    <FooterBar activeTabKey="me" />
  </view>
</template>

<script>
import { get as _get } from 'lodash'
import store from '@/store/index'
import { replaceCosDomainName  } from '@/utils/variables.js'
import { COS_DOMAIN_NAME, openUrl, scaleImageWidthInCOS } from '@/utils'
import { getUserInfo, logout } from '@/api'
import FooterBar from '@/components/footer_bar/index.vue'

const FEATURE_OPTIONS = [
  {
    name: '我的音乐',
    url: '/pages/music/index?type=3',
    jumpTo: 'navigate'
  },
  {
    name: '我的视频',
    url: '/pages/video/index?type=3',
    jumpTo: 'navigate'
  },
  {
    name: '我的文章',
    url: '/pages/article/index?type=6',
    jumpTo: 'navigate'
  },
  {
    name: '我的书单',
    url: '/pages/book/index',
    jumpTo: 'navigate'
  },
  {
    name: '我的成绩',
    url: '/pages/article/index?type=1',
    jumpTo: 'navigate'
  }
]

const BASE_OPTIONS = [
  {
    key: 'cache',
    name: '清除缓存',
  },
  {
    key: 'about',
    name: '关于',
  },
]

export default {
  components: {
    FooterBar
  },
  data() {
    return {
      defaultAvatar: scaleImageWidthInCOS(`${COS_DOMAIN_NAME}/images/snowman-8755896_1280.png`, 160),
      featureOptions: FEATURE_OPTIONS,
      baseOptions: BASE_OPTIONS
    };
  },
  computed: {
    userInfo () {
      return _get(store, 'state.userInfo')
    },
    activeTabKey () {
      return store.state.activeTabKey
    }
  },
  created() {
    store.commit('setActiveTabKey', 'me')
    this.fetchData();
  },
  methods: {
    openUrl,
    replaceCosDomainName,
    fetchData() {
      return getUserInfo().then((data) => {
        store.commit('setUserInfo', data)
      })
    },
    getRoleLabel(role) {
      const map = {
        1: '超级管理员',
        2: '家长',
        3: '学生'
      };
      return map[role] || '未知角色';
    },
    onClickOther (item) {
      if (item.key === 'cache') {
        uni.clearStorageSync();
        uni.showToast({
          title: '缓存已清除！',
          duration: 3000,
          icon: 'success'
        });
        return
      }
      if (item.key === 'about') {
        uni.navigateTo({
          url: '/pages/me/about'
        })
      }
    },
    gotoLogin () {
      uni.navigateTo({
        url: '/pages/login/index',
        fail (error) {
          uni.showModal({
            title: '请求异常',
            content: error.errMsg,
            showCancel: false
          });
        }
      });
    },
    onChangePassword () {
      uni.navigateTo({
        url: '/pages/login/password'
      })
    },
    onLogout() {
      return logout().then(() => {
        store.commit('setIsUseMock', true)
        uni.navigateTo({
          url: '/pages/index/index'
        })
      })
      .catch(error => {
        uni.showToast({
          title: '登出失败',
          icon: 'none'
        })
      })
    }
  }
};
</script>

<style lang="less">
@import './index.less';
</style>

// react-native-expo/src/pages/me.tsx
import { styles } from './me.styles';
import { useCallback, useEffect, useState } from 'react';
import { Alert, Image, ImageBackground, Linking, Pressable, ScrollView, Text, View } from 'react-native';
import { Ionicons } from '@react-native-vector-icons/ionicons';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { router, useFocusEffect } from 'expo-router';
import { AppFooter } from '@/components/AppFooter';
import { appAssets } from '@/config/assets';
import { scaleCosImage } from '@/common/utils/cos';
import { api, type ApiItem } from '@/lib/api';

const avatar = scaleCosImage(appAssets.profileAvatar, 160);
const background = scaleCosImage(appAssets.profileBackground, 750);
const loginBackground = scaleCosImage(appAssets.loginBackground, 750);
const features = [
  { name: '我的音乐', href: '/music?type=3' },
  { name: '我的视频', href: '/video?type=3' },
  { name: '我的文章', href: '/article?type=6' },
  { name: '我的书单', href: '/book' },
  { name: '我的成绩', href: '/article?type=1' },
];

const roleLabel = (role: unknown) => ({ 1: '超级管理员', 2: '家长', 3: '学生' }[Number(role)] ?? '未知角色');

export default function MeScreen() {
  const [user, setUser] = useState<ApiItem | null>(null);
  const fetchUser = useCallback(() => {
    void api.user().then(setUser).catch(() => setUser(null));
  }, []);
  useEffect(() => { fetchUser(); }, [fetchUser]);
  useFocusEffect(fetchUser);

  const clearCache = () => {
    AsyncStorage.clear().then(() => Alert.alert('提示', '缓存已清除！')).catch(() => Alert.alert('提示', '清除缓存失败'));
  };
  const logout = () => {
    api.logout().then(() => {
      setUser(null);
      router.replace('/');
    }).catch(() => Alert.alert('提示', '登出失败'));
  };

  return (
    <View style={styles.page}>
      <ScrollView contentContainerStyle={styles.content}>
        {user ? (
          <ImageBackground source={{ uri: background }} style={styles.profileBackground}>
            <View style={styles.userInfo}>
              <View style={styles.avatarWrap}>
                <Image source={{ uri: avatar }} style={styles.avatar} />
              </View>
              <View>
                <View style={styles.nameRow}>
                  <Text style={styles.name}>{String(user.nickname ?? user.name ?? '')}</Text>
                  <Text style={styles.role}>{roleLabel(user.role)}</Text>
                </View>
                <Pressable onPress={() => Linking.openURL(`tel:${String(user.phone_number ?? '')}`)}>
                  <Text style={styles.phone}>{String(user.phone_number ?? '')}</Text>
                </Pressable>
              </View>
            </View>
          </ImageBackground>
        ) : (
          <ImageBackground source={{ uri: loginBackground }} style={styles.loginBackground}>
            <Pressable onPress={() => router.push('/login')} style={styles.loginButton}>
              <Text style={styles.loginText}>登录</Text>
            </Pressable>
          </ImageBackground>
        )}

        <View style={styles.main}>
          <View style={styles.group}>
            {features.map(item => (
              <Row key={item.name} label={item.name} onPress={() => router.push(item.href as never)} />
            ))}
          </View>
          <View style={styles.group}>
            <Row label="清除缓存" onPress={clearCache} />
            <Row label="关于" onPress={() => router.push('/me/about')} />
          </View>
        </View>
        {user && (
          <View style={styles.actions}>
            <Pressable onPress={() => router.push('/login/password')}>
              <Text style={styles.action}>修改密码</Text>
            </Pressable>
            <Text style={styles.separator}>|</Text>
            <Pressable onPress={logout}>
              <Text style={styles.action}>退出登录</Text>
            </Pressable>
          </View>
        )}
      </ScrollView>
      <AppFooter active="me" />
    </View>
  );
}

function Row({ label, onPress }: { label: string; onPress: () => void }) {
  return (
    <Pressable onPress={onPress} style={styles.row}>
      <Text style={styles.rowText}>{label}</Text>
      <Ionicons name="chevron-forward" size={18} color="#ccc" />
    </Pressable>
  );
}
