// uni-vite/src/pages/task/detail.vue
<template>
  <view v-if="task" class="task_detail">
    <view class="task_detail_title">
      {{ task.title }}
    </view>
    <view v-if="task.publisher" class="task_detail_author">
      {{ task.publisher }}
    </view>

    <view class="task_detail_item">
      <view class="item_label">任务人</view>
      <view class="item_value">{{ task.targeter || '' }}</view>
    </view>

    <view v-if="task.publishTime || task.publishTime === 0" class="task_detail_item">
      <view class="item_label">发布时间</view>
      <view class="item_value">{{ parseTime(task.publishTime, '{y}-{m}-{d}') }}</view>
    </view>

    <view v-if="task.startTime || task.startTime === 0" class="task_detail_item">
      <view class="item_label">开始时间</view>
      <view class="item_value">{{ parseTime(task.startTime, '{y}-{m}-{d}') }}</view>
    </view>

    <view v-if="task.endTime || task.endTime === 0" class="task_detail_item">
      <view class="item_label">结束时间</view>
      <view class="item_value">{{ parseTime(task.endTime, '{y}-{m}-{d}') }}</view>
    </view>

    <view class="task_detail_item">
      <view class="item_label">任务内容</view>
      <view class="item_value">{{ task.content || '' }}</view>
    </view>

    <view class="task_detail_item">
      <view class="item_label">验收标准</view>
      <view class="item_value">{{ task.finished || '' }}</view>
    </view>

    <view class="task_detail_item">
      <view class="item_label">状态</view>
      <view class="item_value">
        <view class="item_value_status" :class="`status_${task.status}`">
          {{ statusMap[task.status] }}
        </view>
      </view>
    </view>

    <view class="task_detail_item">
      <view class="item_label">进度</view>
      <view class="item_value">
        <view class="progress_wrap">
          <view class="progress_bar">
            <view class="progress_inner" :style="{ width: task.progress + '%' }"></view>
          </view>
          <view class="progress_text">{{ task.progress }}%</view>
        </view>
      </view>
    </view>

    <view v-if="task.awards && task.awards.length" class="task_detail_item block">
      <view class="item_label">奖励</view>
      <view class="item_value">
        <ArticleDetail :articleData="task.awards" />
      </view>
    </view>

    <view v-if="task.attachments && task.attachments.length" class="task_detail_item block">
      <view class="item_label">附件</view>
      <view class="item_value">
        <ArticleDetail :articleData="task.attachments" />
      </view>
    </view>

    <view v-if="task.works && task.works.length" class="task_detail_item block">
      <view class="item_label">作品</view>
      <view class="item_value">
        <ArticleDetail :articleData="task.works" />
      </view>
    </view>
  </view>
</template>

<script>
import { getTaskById } from '@/api/index.js'
import { parseTime } from '@/utils/index.js'
import { TASK_STATUS_ENUM } from './constant.js'
import ArticleDetail from '@/components/article_detail/index.vue'

export default {
  components: {
    ArticleDetail
  },
  data () {
    return {
      task: null,
      statusMap: TASK_STATUS_ENUM,
    }
  },
  onLoad (options) {
    const id = options && options.id
    if (id) {
      return getTaskById({id}).then((data) => {
        this.task = data || {}
      })
    }
  },
  methods: {
    parseTime
  }
}
</script>

<style lang="less">
@import './detail.less';
</style>

// react-native-expo/src/pages/task/detail.tsx
import { styles } from './detail.styles';
import { useEffect, useState } from 'react';
import { ScrollView, Text, View } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { api, type ApiItem } from '@/lib/api';

const statuses: Record<string, string> = { '1': '未开始', '2': '进行中', '3': '已完成', '4': '已取消' };

function date(value: unknown) {
  const time = new Date(Number(value));
  return Number.isNaN(time.getTime()) ? '' : `${time.getFullYear()}-${String(time.getMonth() + 1).padStart(2, '0')}-${String(time.getDate()).padStart(2, '0')}`;
}

function text(value: unknown) {
  return String(value ?? '').replace(/<[^>]*>/g, '').replace(/&nbsp;/g, ' ').trim();
}

function DetailBlocks({ data }: { data: unknown }) {
  const blocks = Array.isArray(data) ? data : [];
  return <View>{blocks.map((block, index) => {
    const item = block as ApiItem;
    const content = Array.isArray(item.content) ? item.content : [item.content];
    return <View key={`${String(item.type)}-${index}`} style={styles.block}>
      {content.filter(Boolean).map((value, contentIndex) => <Text key={contentIndex} style={styles.blockText}>{text(value)}</Text>)}
    </View>;
  })}</View>;
}

export default function TaskDetailScreen() {
  const { id } = useLocalSearchParams<{ id?: string }>();
  const [task, setTask] = useState<ApiItem | null>(null);

  useEffect(() => { if (id) api.task(id).then(value => setTask(value ?? null)).catch(() => setTask(null)); }, [id]);
  if (!task) return <View style={styles.loading}><Text style={styles.loadingText}>加载中…</Text></View>;

  const progress = Math.max(0, Math.min(100, Number(task.progress ?? 0)));
  const detail = (label: string, value: unknown) => <View style={styles.item} key={label}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{text(value)}</Text></View>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}>
    <Text style={styles.title}>{text(task.title)}</Text>
    {!!task.publisher && <Text style={styles.author}>{text(task.publisher)}</Text>}
    {detail('任务人', task.targeter)}
    {task.publishTime !== undefined && detail('发布时间', date(task.publishTime))}
    {task.startTime !== undefined && detail('开始时间', date(task.startTime))}
    {task.endTime !== undefined && detail('结束时间', date(task.endTime))}
    {detail('任务内容', task.content)}
    {detail('验收标准', task.finished)}
    <View style={styles.item}><Text style={styles.label}>状态</Text><View style={[styles.status, styles[`status${String(task.status)}` as keyof typeof styles]]}><Text style={styles.statusText}>{statuses[String(task.status)] ?? '未知'}</Text></View></View>
    <View style={styles.item}><Text style={styles.label}>进度</Text><View style={styles.progressWrap}><View style={styles.track}><View style={[styles.progress, { width: `${progress}%` }]} /></View><Text style={styles.progressText}>{progress}%</Text></View></View>
    {(['awards', 'attachments', 'works'] as const).map(key => Array.isArray(task[key]) && task[key].length > 0 && <View style={styles.section} key={key}><Text style={styles.sectionTitle}>{({ awards: '奖励', attachments: '附件', works: '作品' })[key]}</Text><DetailBlocks data={task[key]} /></View>)}
  </ScrollView>;
}
