// react-native-expo/src/pages/study/dictation.tsx
import { styles } from './dictation.styles';
import { useEffect, useMemo, useRef, useState } from 'react';
import { Alert, Modal, Pressable, SafeAreaView, ScrollView, Text, TextInput, View } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import * as Speech from 'expo-speech';
import { pinyin } from 'pinyin-pro';
import { api } from '@/lib/api';

type Word = { word: string; pinyin: string };
type Status = 'pending' | 'active' | 'finished';
const gradeOptions = Array.from({ length: 12 }, (_, index) => ({ value: index + 1, label: `${['一', '一', '二', '二', '三', '三', '四', '四', '五', '五', '六', '六'][index]}（${index % 2 ? '下' : '上'}）` }));
const splitWords = (value: string) => value.split(/[\s,，、;；]+/).map(word => word.trim()).filter(Boolean);
const wordItems = (words: string[]) => words.map(word => ({ word, pinyin: pinyin(word, { toneType: 'symbol' }) }));
const clamp = (value: string, min: number, max: number) => Math.max(min, Math.min(max, Number(value) || min));

export default function DictationScreen() {
  const { id, words: rawWords, note: rawNote } = useLocalSearchParams<{ id?: string; words?: string; note?: string }>();
  const note = useMemo(() => { try { return decodeURIComponent(rawNote ?? ''); } catch { return rawNote ?? ''; } }, [rawNote]);
  const initialWords = useMemo(() => { try { return splitWords(decodeURIComponent(rawWords ?? '')); } catch { return splitWords(rawWords ?? ''); } }, [rawWords]);
  const [allWords, setAllWords] = useState<Word[]>(() => wordItems(initialWords));
  const [selected, setSelected] = useState<string[]>(initialWords);
  const [status, setStatus] = useState<Status>('pending');
  const [completed, setCompleted] = useState<Set<number>>(new Set());
  const [current, setCurrent] = useState(0);
  const [paused, setPaused] = useState(false);
  const [settingsVisible, setSettingsVisible] = useState(false);
  const [interval, setIntervalSeconds] = useState(20);
  const [grade, setGrade] = useState(1);
  const timer = useRef<ReturnType<typeof setInterval> | null>(null);

  const available = useMemo(() => allWords.map(item => item.word), [allWords]);
  const chosen = useMemo(() => allWords.filter(item => selected.includes(item.word)), [allWords, selected]);
  const clearTimer = () => { if (timer.current) clearInterval(timer.current); timer.current = null; };
  const stop = () => { clearTimer(); Speech.stop(); };
  useEffect(() => () => stop(), []);
  useEffect(() => {
    if (initialWords.length || !id) return;
    api.words({ id, pageNum: 0, pageSize: 20 }).then(result => {
      const list = result.content ?? [];
      const first = String(list[0]?.words ?? '');
      const next = wordItems(splitWords(first));
      setAllWords(next); setSelected(next.map(item => item.word));
    }).catch(() => undefined);
  }, [id, initialWords.length]);
  useEffect(() => { if (note) Speech.speak(note, { language: 'zh-CN' }); }, [note]);

  const speakCurrent = (index = current) => {
    const item = chosen[index];
    if (!item) return;
    clearTimer();
    Speech.stop();
    Speech.speak(item.word, { language: 'zh-CN' });
    let repeats = 0;
    timer.current = setInterval(() => {
      repeats += 1;
      if (repeats < 3) Speech.speak(item.word, { language: 'zh-CN' });
      else { clearTimer(); advance(index); }
    }, Math.max(1000, (interval * 1000) / 4));
  };
  const advance = (index = current) => {
    stop();
    setCompleted(previous => new Set(previous).add(index));
    if (index + 1 >= chosen.length) { setStatus('finished'); setPaused(false); return; }
    setCurrent(index + 1);
    speakCurrent(index + 1);
  };
  const start = () => { if (!chosen.length) return; setStatus('active'); setCompleted(new Set()); setCurrent(0); setPaused(false); speakCurrent(0); };
  const restart = () => { stop(); setStatus('pending'); setCompleted(new Set()); setCurrent(0); setPaused(false); };
  const togglePause = () => {
    if (paused) { setPaused(false); speakCurrent(); } else { clearTimer(); Speech.stop(); setPaused(true); }
  };
  const randomizeCount = (value: string) => {
    const count = clamp(value, 1, available.length || 1);
    const pool = [...available].sort(() => Math.random() - .5);
    setSelected(pool.slice(0, count));
  };
  const visible = status === 'active' ? chosen.filter((_, index) => completed.has(index)) : chosen;

  return <SafeAreaView style={styles.page}>
    <ScrollView contentContainerStyle={styles.content}>{note ? <View style={styles.note}><Text style={styles.noteText}>{note}</Text></View> : null}
      {!allWords.length ? <View style={styles.empty}><Text style={styles.emptyTitle}>暂无词语</Text><Text style={styles.emptyText}>请打开设置弹层选择词语。</Text></View> : <View style={styles.grid}>{visible.map((item, index) => <Pressable key={`${item.word}-${index}`} onPress={() => { stop(); Speech.speak(item.word, { language: 'zh-CN' }); }} style={[styles.card, status === 'active' && styles.done, status === 'finished' && !completed.has(index) && styles.todo]}><Text style={styles.cardWord}>{item.word}</Text><Text numberOfLines={1} style={styles.cardPinyin}>{item.pinyin}</Text></Pressable>)}</View>}
    </ScrollView>
    <View style={styles.bottom}>{chosen.length ? <Text style={styles.progress}>当前共 <Text style={styles.progressNum}>{chosen.length}</Text> 个{status === 'active' ? <>，已完成 <Text style={styles.progressNum}>{completed.size}</Text> 个，剩余 <Text style={styles.progressNum}>{Math.max(0, chosen.length - completed.size)}</Text> 个</> : null}</Text> : null}<View style={styles.actions}>{status === 'pending' ? <><Pressable style={styles.outline} onPress={() => setSettingsVisible(true)}><Text>设置</Text></Pressable><Pressable style={[styles.primary, !chosen.length && styles.disabled]} onPress={start}><Text style={styles.buttonText}>开始听写</Text></Pressable></> : status === 'active' ? <><Pressable style={styles.danger} onPress={() => { stop(); setStatus('finished'); }}><Text style={styles.dangerText}>结束</Text></Pressable><Pressable style={styles.warning} onPress={togglePause}><Text style={styles.warningText}>{paused ? '继续' : '暂停'}</Text></Pressable><Pressable style={[styles.primary, paused && styles.disabled]} onPress={() => !paused && advance()}><Text style={styles.buttonText}>下一个</Text></Pressable></> : <Pressable style={styles.primary} onPress={restart}><Text style={styles.buttonText}>重新开始</Text></Pressable>}</View></View>
    <Modal visible={settingsVisible} transparent animationType="slide" onRequestClose={() => setSettingsVisible(false)}><View style={styles.mask}><View style={styles.sheet}><Text style={styles.sheetTitle}>设置</Text><ScrollView contentContainerStyle={styles.sheetBody}><Text style={styles.fieldLabel}>间隔时间</Text><TextInput value={String(interval)} onChangeText={value => setIntervalSeconds(clamp(value, 1, 120))} keyboardType="number-pad" style={styles.input} placeholder="请输入词语听写的间隔时间（秒）" /><Text style={styles.fieldLabel}>年级</Text><View style={styles.chips}>{gradeOptions.map(option => <Pressable key={option.value} onPress={() => setGrade(option.value)} style={[styles.chip, grade === option.value && styles.chipActive]}><Text style={grade === option.value && styles.chipActiveText}>{option.label}</Text></Pressable>)}</View><Text style={styles.fieldLabel}>词语数量</Text><TextInput value={String(selected.length)} onEndEditing={event => randomizeCount(event.nativeEvent.text)} keyboardType="number-pad" style={styles.input} /><Text style={styles.fieldLabel}>选择词语</Text><View style={styles.chips}>{available.map(word => <Pressable key={word} onPress={() => setSelected(old => old.includes(word) ? old.filter(item => item !== word) : [...old, word])} style={[styles.chip, selected.includes(word) && styles.chipActive]}><Text style={selected.includes(word) && styles.chipActiveText}>{word}</Text></Pressable>)}</View></ScrollView><View style={styles.sheetActions}><Pressable style={styles.outline} onPress={() => setSettingsVisible(false)}><Text>取消</Text></Pressable><Pressable style={styles.primary} onPress={() => { if (!selected.length) return Alert.alert('提示', '请至少选择一个词语'); restart(); setSettingsVisible(false); }}><Text style={styles.buttonText}>确认</Text></Pressable></View></View></View></Modal>
  </SafeAreaView>;
}

// uni-vite/src/pages/study/dictation/index.vue
<template>
  <view v-if="isLoaded" class="page" :class="{ page_no_scroll: settingsVisible }">
    <view v-if="noteText" class="note">
      <text class="note_text">{{ noteText }}</text>
    </view>

    <view v-if="wordLength === 0" class="empty">
      <text class="empty_title">暂无词语</text>
      <text class="empty_desc">请打开设置弹层选择词语。</text>
    </view>

    <view v-else class="grid">
      <view
        v-for="(item, idx) in visibleWordList"
        :key="item.word + '_' + item._i + '_' + idx"
        class="card"
        :class="cardClass(item._i)"
        @click="onClickCard(item)"
      >
        <view class="card_word">{{ item.word }}</view>
        <view class="card_pinyin">{{ item.pinyin }}</view>
      </view>
    </view>

    <view class="bottom_stack">
      <view v-if="selectedWordLength" class="progress_dock">
        <view class="progress_inner">
          <text class="progress_muted">当前共 </text>
          <text class="progress_num">{{ selectedWordLength }}</text>
          <text class="progress_muted"> 个 </text>
          <text v-if="status === 'active'" class="progress_muted"> ，已完成 </text>
          <text v-if="status === 'active'" class="progress_num">{{ completedCount }}</text>
          <text v-if="status === 'active'" class="progress_muted"> 个，剩余 </text>
          <text v-if="status === 'active'" class="progress_num">{{ remainingCount }}</text>
          <text v-if="status === 'active'" class="progress_muted"> 个</text>
        </view>
      </view>
      <view class="footer">
        <template v-if="status === 'pending'">
          <button class="btn btn_settings btn_sm" @click="openSettings">设置</button>
          <button v-if="selectedWordLength" class="btn btn_primary btn_lg" :disabled="selectedWordLength === 0" @click="start">
            开始听写
          </button>
        </template>

        <template v-else-if="status === 'active'">
          <button class="btn btn_danger btn_sm" @click="finishEarly">结束</button>
          <button class="btn btn_warn btn_md" @click="togglePause">{{ pauseLabel }}</button>
          <button class="btn btn_primary btn_lg" :disabled="isPaused || selectedWordLength === 0" @click="next">
            下一个
          </button>
        </template>

        <template v-else>
          <button class="btn btn_primary btn_lg" :disabled="selectedWordLength === 0" @click="restart">重新开始</button>
        </template>
      </view>
    </view>

    <view v-if="settingsVisible" class="mask" @click.self="closeSettings" @touchmove.stop.prevent>
      <view class="sheet" @touchmove.stop>
        <view class="sheet_hd">
          <view class="sheet_title">设置</view>
        </view>

        <scroll-view scroll-y class="sheet_bd">
          <view class="form_row">
            <view class="form_row_label">间隔时间</view>
            <view class="form_row_field">
              <input
                class="input"
                type="number"
                :value="settings.intervalTime"
                @input="onInputInterval"
                placeholder="请输入词语听写的间隔时间（秒）"
              />
            </view>
          </view>

          <view v-if="!hasLinkParams" class="form_row">
            <view class="form_row_label">年级</view>
            <view class="form_row_field">
              <view class="chip_row">
                <view
                  v-for="(opt, i) in gradeOptions"
                  :key="opt.value"
                  class="chip"
                  :class="{ chip_active: settings.gradeKey === opt.value }"
                  @click="pickGrade(opt.value, i)"
                >
                  {{ opt.label }}
                </view>
              </view>
            </view>
          </view>

          <view v-if="wordLength" class="form_row">
            <view class="form_row_label">词语数量</view>
            <view class="form_row_field">
              <input
                class="input"
                type="number"
                :value="settings.wordCount"
                @input="onInputWordCount"
                @blur="onBlurWordCount"
                placeholder="请输入随机抽取的词语数量"
              />
            </view>
          </view>

          <view>
            <view class="word_pick_title">选择词语</view>
            <view class="word_pick_grid">
              <view
                v-for="w in settings.availableWords"
                :key="w"
                class="word_chip"
                :class="{ word_chip_on: settings.selectedWords.includes(w) }"
                @click="toggleWord(w)"
              >
                {{ w }}
              </view>
            </view>
          </view>
        </scroll-view>

        <view class="sheet_ft">
          <button class="btn_cancel_sheet" @click="closeSettings">取消</button>
          <button class="btn_ok_sheet" @click="confirmSettings">确认</button>
        </view>
      </view>
    </view>
  </view>
</template>

<script>
import { get as _get } from 'lodash'
import { TTSManager } from '@/common/js/TTSManager.js'
import { getChineseWordList } from '@/api'
import { clampNumber, splitWords, toPinyinSymbol } from '@/utils/dictation.js'


function buildWordList (words) {
  return (words || []).map(w => ({
    word: w,
    pinyin: toPinyinSymbol(w)
  }))
}

export default {
  data () {
    return {
      isLoaded: false,
      status: 'pending',
      noteText: '',
      routeId: '',
      routeWordsRaw: '',
      allWordList: [],
      wordList: [],
      completedSet: new Set(),
      currentIndex: 0,
      waitingTimer: null,
      pausedDuringWait: false,
      isPaused: false,
      settingsVisible: false,
      settings: {
        intervalTime: 20,
        gradeKey: 1,
        availableWords: [],
        selectedWords: [],
        wordCount: 0
      },
    }
  },
  computed: {
    hasLinkParams () {
      if (this.routeId) return true
      return splitWords(this.routeWordsRaw).length > 0
    },
    wordLength () {
      return this.wordList.length
    },
    selectedWordList () {
      const { wordList, settings } = this
      let list = wordList
      if (settings.selectedWords.length > 0) {
        list = wordList.filter(x => settings.selectedWords.includes(x.word))
      }
      return list
    },
    selectedWordLength () {
      return this.selectedWordList.length
    },
    visibleWordList () {
      const mapItem = (item, idx) => ({ ...item, _i: idx })
      if (this.status === 'active') {
        return this.selectedWordList
          .map(mapItem)
          .filter(x => this.completedSet.has(x._i))
      }
      return this.selectedWordList.map(mapItem)
    },
    completedCount () {
      return this.completedSet.size
    },
    remainingCount () {
      return Math.max(0, this.selectedWordLength - this.completedCount)
    },
    pauseLabel () {
      return this.isPaused ? '继续' : '暂停'
    },
    gradeOptions () {
      let options = [
        { value: 1, label: '一（上）' },
        { value: 2, label: '一（下）' },
        { value: 3, label: '二（上）' },
        { value: 4, label: '二（下）' },
        { value: 5, label: '三（上）' },
        { value: 6, label: '三（下）' },
        { value: 7, label: '四（上）' },
        { value: 8, label: '四（下）' },
        { value: 9, label: '五（上）' },
        { value: 10, label: '五（下）' },
        { value: 11, label: '六（上）' },
        { value: 12, label: '六（下）' }
      ]
      const existGradeIds = this.allWordList.map(e => e.gradeId)
      if (existGradeIds.length > 0) {
        options = options.filter(e => existGradeIds.includes(e.value))
      }
      return options
    }
  },
  async onLoad (options = {}) {
    this.routeId = _get(options, 'id', '') || ''
    this.routeWordsRaw = decodeURIComponentSafe(_get(options, 'words', ''))
    this.noteText = decodeURIComponentSafe(_get(options, 'note', ''))

    const words = splitWords(this.routeWordsRaw)
    this.wordList = buildWordList(words)
    if (!words.length) {
      await this.getChineseWordList(this.routeId).catch(() => {})
    }

    this.isLoaded = true
    this.resetSettingsAvailableWords()

    this.$nextTick(() => {
      if (this.noteText) {
        TTSManager.speak(this.noteText)
      }
    })
  },
  beforeUnmount () {
    this.clearWaiting()
    try { TTSManager.stop() } catch (e) {}
  },
  methods: {
    getChineseWordList (id) {
      return getChineseWordList({
        id,
        pageNum: 0,
        pageSize: 20
      }).then(data => {
        this.allWordList = _get(data, 'content', [])
        this.wordList = buildWordList(splitWords(_get(data, 'content[0].words', '')))
        return data
      })
    },
    resetSettingsAvailableWords () {
      const { wordList, settings } = this
      const list = (wordList || []).map(e => e.word)
      settings.availableWords = Array.from(new Set(list)).filter(Boolean)
      settings.selectedWords = (settings.selectedWords || []).filter(w => settings.availableWords.includes(w))
      if (settings.selectedWords.length === 0) {
        settings.selectedWords = [...settings.availableWords]
      }
      settings.wordCount = clampNumber(settings.selectedWords.length, 1, settings.availableWords.length)
    },
    openSettings () {
      if (this.status !== 'pending') return
      this.resetSettingsAvailableWords()
      this.settingsVisible = true
    },
    closeSettings () {
      this.settingsVisible = false
    },
    onInputInterval (e) {
      const v = _get(e, 'detail.value')
      this.settings.intervalTime = clampNumber(v, 1, 120)
    },
    pickGrade (value, i) {
      const words = this.allWordList.find(e => e.gradeId === value)?.words || ''
      this.settings.gradeKey = value
      this.wordList = buildWordList(splitWords(words))
      this.resetSettingsAvailableWords()
    },
    toggleWord (w) {
      const word = String(w)
      const set = new Set(this.settings.selectedWords)
      if (set.has(word)) set.delete(word)
      else set.add(word)
      this.settings.selectedWords = Array.from(set)
      this.settings.wordCount = clampNumber(this.settings.selectedWords.length, 1, this.settings.availableWords.length)
    },
    onInputWordCount (e) {
      const v = _get(e, 'detail.value')
      const maxN = this.settings.availableWords.length || 1
      this.settings.wordCount = clampNumber(v, 1, maxN)
    },
    onBlurWordCount () {
      const maxN = this.settings.availableWords.length || 1
      let n = clampNumber(this.settings.wordCount, 1, maxN)
      this.settings.wordCount = n
      const pool = [...this.settings.availableWords]
      for (let i = pool.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1))
        const t = pool[i]
        pool[i] = pool[j]
        pool[j] = t
      }
      this.settings.selectedWords = pool.slice(0, n)
    },
    confirmSettings () {
      const words = (this.settings.selectedWords || []).filter(Boolean)
      if (words.length === 0) {
        uni.showToast({ title: '请至少选择一个词语', icon: 'none' })
        return
      }
      this.restart()
      this.settingsVisible = false
    },
    start () {
      if (!this.selectedWordLength) return
      this.status = 'active'
      this.completedSet = new Set()
      this.currentIndex = 0
      this.isPaused = false
      this.pausedDuringWait = false
      this.clearWaiting()
      this.speakCurrent()
    },
    restart () {
      this.clearWaiting()
      this.pausedDuringWait = false
      try { TTSManager.stop() } catch (e) {}
      this.status = 'pending'
      this.completedSet = new Set()
      this.currentIndex = 0
      this.isPaused = false
    },
    finishEarly () {
      this.clearWaiting()
      this.pausedDuringWait = false
      this.status = 'finished'
      try { TTSManager.stop() } catch (e) {}
      this.isPaused = false
    },
    togglePause () {
      if (this.status !== 'active') return
      if (this.isPaused) {
        this.isPaused = false
        if (this.pausedDuringWait) {
          this.pausedDuringWait = false
          this.speakCurrent()
        } else {
          try { TTSManager.resume() } catch (e) {}
        }
        return
      }
      this.pausedDuringWait = !!this.waitingTimer
      this.isPaused = true
      this.clearWaiting()
      try { TTSManager.pause() } catch (e) {}
    },
    clearWaiting () {
      if (this.waitingTimer) {
        clearInterval(this.waitingTimer)
        this.waitingTimer = null
      }
    },
    cardClass (realIdx) {
      const done = this.completedSet.has(realIdx)
      if (this.status === 'finished') {
        return done ? 'done' : 'todo'
      }
      if (this.status === 'active') return 'done'
      return ''
    },
    onClickCard (item) {
      if (!item || !item.word) return
      this.clearWaiting()
      TTSManager.speak(item.word)
    },
    async speakCurrent () {
      if (this.status !== 'active') return
      if (this.isPaused) return
      const item = this.selectedWordList[this.currentIndex]
      if (!item) return

      this.clearWaiting()
      const intervalSec = this.settings.intervalTime || 20
      const gapMs = Math.max(1000, Math.floor((intervalSec * 1000) / 4))
      let repeatCount = 0
      TTSManager.speak(item.word)
      this.waitingTimer = setInterval(() => {
        if (this.status !== 'active' || this.isPaused) return
        repeatCount ++
        if (repeatCount < 3) {
          TTSManager.speak(item.word)
        }
        if (repeatCount >= 4) {
          this.clearWaiting()
          this.completeAndAdvance()
        }
      }, gapMs)
    },
    next () {
      if (this.status !== 'active') return
      if (this.isPaused) return
      this.completeAndAdvance()
    },
    completeAndAdvance () {
      this.clearWaiting()
      try { TTSManager.stop() } catch (e) {}

      const idx = this.currentIndex
      if (!this.completedSet.has(idx)) {
        const nextSet = new Set(this.completedSet)
        nextSet.add(idx)
        this.completedSet = nextSet
      }

      const nextIndex = idx + 1
      if (nextIndex >= this.selectedWordList.length) {
        this.status = 'finished'
        this.isPaused = false
        return
      }
      this.currentIndex = nextIndex
      this.speakCurrent()
    }
  }
}

function decodeURIComponentSafe (s) {
  try {
    return decodeURIComponent(String(s || ''))
  } catch (e) {
    return String(s || '')
  }
}
</script>

<style lang="less" scoped>
@import './index.less';
</style>
