// react-native-expo/src/pages/book/detail.tsx
import { styles } from './detail.styles';
import { useEffect, useState } from 'react';
import { Image, Pressable, ScrollView, Text, View } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { api, type ApiItem } from '@/lib/api';

function thumbnail(uri: unknown) {
  return typeof uri === 'string' ? `${uri}${uri.includes('?') ? '&' : '?'}imageMogr2/thumbnail/320x` : undefined;
}
function clean(value: unknown) {
  return String(value ?? '').replace(/<br\s*\/?>/gi, '\n').replace(/<[^>]*>/g, '').replace(/&nbsp;/g, ' ').trim();
}
function values(value: unknown) {
  return Array.isArray(value) ? value : [value];
}

export default function BookDetailScreen() {
  const { id } = useLocalSearchParams<{ id?: string }>();
  const [book, setBook] = useState<ApiItem | null>(null);
  useEffect(() => { if (id) api.book(id).then(value => setBook(value ?? null)).catch(() => setBook(null)); }, [id]);
  if (!book) return <View style={styles.loading}><Text style={styles.muted}>加载中…</Text></View>;

  const score = Number(book.score ?? 0);
  const bookTags = Array.isArray(book.tags) ? book.tags : [];

  return (
    <ScrollView style={styles.page} contentContainerStyle={styles.content}>
      <View style={styles.overview}>
        <Pressable>
          <Image source={{ uri: thumbnail(book.cover) }} style={styles.cover} />
        </Pressable>
        <View style={styles.info}>
          <Text style={styles.title}>{String(book.title ?? '')}</Text>
          <Text style={styles.meta}>作者：{String(book.author ?? '')}</Text>
          <Text style={styles.meta}>书主：{String(book.owner ?? '')}</Text>
          {score > 0 && (
            <View style={styles.rating}>
              <Text style={styles.ratingLabel}>评分：</Text>
              <Text style={styles.ratingNumber}>{score.toFixed(1)}</Text>
              <Text style={styles.stars}>
                {[1, 2, 3, 4, 5].map(n => n <= Math.round(score / 2) ? '★' : '☆').join('')}
              </Text>
            </View>
          )}
          <View style={styles.tags}>
            {bookTags.map(tag => (
              <Text key={String(tag)} style={styles.tag}>{String(tag)}</Text>
            ))}
          </View>
        </View>
      </View>
      <View style={styles.body}>
        {Boolean(book.summaries) && (
          <View style={styles.card}>
            <Text style={styles.cardTitle}>书籍简介</Text>
            {values(book.summaries).filter(Boolean).map((summary, index) => (
              <Text key={index} style={styles.summary}>{clean(summary)}</Text>
            ))}
          </View>
        )}
        {Array.isArray(book.highlights) && book.highlights.length > 0 && (
          <View style={styles.card}>
            <Text style={styles.cardTitle}>精彩内容</Text>
            <View style={styles.highlights}>
              {book.highlights.map((highlight, index) => (
                <View key={index} style={styles.highlight}>
                  <Text style={styles.highlightText}>{clean(highlight)}</Text>
                </View>
              ))}
            </View>
          </View>
        )}
      </View>
    </ScrollView>
  );
}

// uni-vite/src/pages/book/detail.vue
<template>
  <view v-if="book" class="book_detail_page" scroll-y>
    <view class="overview">
      <image class="cover" :src="book.cover + '?imageMogr2/thumbnail/160x'" mode="aspectFill" />
      <view class="info">
        <text class="title">{{ book.title }}</text>
        <view class="meta">
          <text class="meta_label">作者：</text>
          <text class="meta_value">{{ book.author }}</text>
        </view>
        <view class="meta">
          <text class="meta_label">书主：</text>
          <text class="meta_value">{{ book.owner }}</text>
        </view>
        <view v-if="book.score" class="rating">
          <text class="rating_label">评分：</text>
          <text class="rating_value">{{ book.score.toFixed(1) }}</text>
          <view class="rating_stars">
            <text
              v-for="n in 5"
              :key="n"
              class="star"
              :class="{ active: n <= Math.round(book.score / 2) }"
            >
              ★
            </text>
          </view>
        </view>
        <view v-if="book.tags && book.tags.length" class="tag">
          <text class="tx" v-for="tag in book.tags" :key="tag">
            {{ tag }}
          </text>
        </view>
      </view>
    </view>

    <view class="book_content">
      <view v-if="book.summaries" class="card">
        <view class="title">书籍简介</view>
        <view v-for="tx in [book.summaries].flat()" class="summary">
          <rich-text :nodes="tx"></rich-text>
        </view>
      </view>

      <view v-if="book.highlights && book.highlights.length" class="card">
        <view class="title">精彩内容</view>
        <view class="highlights">
          <view class="highlight" v-for="(tx, index) in [book.highlights].flat()" :key="index">
            <rich-text class="text" :nodes="tx"></rich-text>
          </view>
        </view>
      </view>
    </view>
  </view>
</template>

<script>
import { getBookById } from '@/api/book.js'
export default {
  data () {
    return {
      book: null
    }
  },
  onLoad (options) {
    const { id } = options
    if (id) {
      return getBookById({ id }).then(data => {
        this.book = data || null
      })
    }
  },
}
</script>

<style lang="less">
@import './detail.less';
</style>
