// react-native-expo/src/pages/book.tsx
import { styles } from './book.styles';
import { useCallback, useEffect, useState } from 'react';
import { Image, Pressable, ScrollView, Text, View } from 'react-native';
import { router } from 'expo-router';
import { AppRefreshControl } from '@/components/AppRefreshControl';
import { useScrollToLower } from '@/common/hooks/useScrollToLower';
import { api, type ApiItem } from '@/lib/api';
import { scaleCosImage } from '@/common/utils/cos';

function thumbnail(uri: unknown) {
  return scaleCosImage(uri, 160);
}

function tags(value: unknown) {
  return Array.isArray(value) ? value.map(String).filter(Boolean) : [];
}

export default function BookScreen() {
  const [books, setBooks] = useState<ApiItem[]>([]);
  const [pageNum, setPageNum] = useState(0);
  const [isLast, setIsLast] = useState(false);
  const [refreshing, setRefreshing] = useState(false);

  const load = useCallback((page: number, append = false) => api.bookPage({ pageNum: page, pageSize: 20 }).then(value => {
    const next = value.content ?? [];
    setBooks(current => (append ? [...current, ...next] : next));
    setPageNum(page);
    setIsLast(next.length < 20);
  }).catch(() => {
    if (!append) setBooks([]);
    setIsLast(true);
  }), []);

  useEffect(() => { void load(0); }, [load]);

  const onRefresh = () => {
    setRefreshing(true);
    void load(0).finally(() => setRefreshing(false));
  };

  const loadMore = () => {
    if (isLast) return;
    void load(pageNum + 1, true);
  };

  const onScrollToLower = useScrollToLower(loadMore, !isLast);

  return (
    <View style={styles.page}>
      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.content}
        refreshControl={<AppRefreshControl refreshing={refreshing} onRefresh={onRefresh} />}
        onScroll={onScrollToLower}
        scrollEventThrottle={16}
      >
        <View style={styles.header}>
          <Text style={styles.heading}>一兆精选 · 图书馆</Text>
          <Text style={styles.subtitle}>沉浸阅读 · 私藏好书随时借阅</Text>
        </View>
        <View style={styles.list}>
          {books.map(book => {
            const cover = thumbnail(book.cover);
            const score = Number(book.score);
            return (
              <Pressable
                key={String(book.id)}
                onPress={() => router.push(`/book/detail?id=${book.id}`)}
                style={styles.card}
              >
                {cover ? (
                  <Image source={{ uri: cover }} style={styles.cover} />
                ) : (
                  <View style={styles.cover} />
                )}
                <View style={styles.info}>
                  <View style={styles.cardHead}>
                    <Text style={styles.title} numberOfLines={1}>{String(book.title ?? '')}</Text>
                    {score > 0 ? (
                      <Text style={styles.score}>
                        {score.toFixed(1)}
                        <Text style={styles.scoreSuffix}>分</Text>
                      </Text>
                    ) : null}
                  </View>
                  <Text style={styles.meta}>作者：{String(book.author ?? '')}</Text>
                  <Text style={styles.meta}>书主：{String(book.owner ?? '')}</Text>
                  <Text style={styles.description} numberOfLines={2}>{String(book.description ?? '')}</Text>
                  <View style={styles.tags}>
                    {tags(book.tags).map(tag => (
                      <View key={tag} style={styles.tag}>
                        <Text style={styles.tagText}>{tag}</Text>
                      </View>
                    ))}
                  </View>
                </View>
              </Pressable>
            );
          })}
          {!books.length && isLast ? <Text style={styles.empty}>~什么都没有哦~</Text> : null}
          {books.length > 0 ? (
            <Text style={styles.more}>{isLast ? '~没有更多了哦~' : '加载中...'}</Text>
          ) : null}
        </View>
      </ScrollView>
    </View>
  );
}

// uni-vite/src/pages/book/index.vue
<template>
  <scroll-view class="book_page" scroll-y="true" @scrolltolower="onScrollToLower" lower-threshold="100">
    <view class="header">
      <view>
        <text class="title">一兆精选 · 图书馆</text>
        <text class="subtitle">沉浸阅读 · 私藏好书随时借阅</text>
      </view>
    </view>

    <view v-if="isLoad" class="book_list">
      <view v-if="bookList && bookList.length" class="book_item" v-for="book in bookList" :key="book.id" @click="onClickCard(book)">
        <image class="book_cover" mode="aspectFill" :src="scaleImageWidthInCOS(book.cover, 160)" />
        <view class="book_content">
          <view class="book_header">
            <text class="book_title">{{ book.title }}</text>
            <view v-if="book.score" class="book_score">
              <text class="score">{{ book.score.toFixed(1) }}</text>
              <text class="suffix">分</text>
            </view>
          </view>

          <view class="book_meta">
            <text>作者：{{ book.author }}</text>
          </view>
          <view class="book_meta">
					  <text>书主：{{ book.owner }}</text>
          </view>

          <text class="book_desc">
            {{ textEllipsis(book.description, 32) }}
          </text>

          <view class="book_tag">
            <text class="tag" v-for="tag in book.tags" :key="tag">
              {{ tag }}
            </text>
          </view>
        </view>
      </view>
      <view v-if="bookList && bookList.length && pagination.isLast" class="nomore_load_tips">
        ~没有更多了哦~
      </view>
      <view v-if="!(bookList && bookList.length)" class="nothing_tips" style="padding-top: 30vh; padding-bottom: 30vh;">
        ~什么都没有哦~
      </view>
    </view>
  </scroll-view>
</template>
<script>
import { get as _get } from 'lodash'
import { textEllipsis, scaleImageWidthInCOS } from '@/utils/common.js'
import { getBookPageList } from '@/api/book.js'

const initPagination = () => ({
  pageNum: 0,
  pageSize: 10,
  isLast: false
})

export default {
  props: {
    queryParams: {
      type: Object,
      default: () => ({})
    }
  },
  data () {
    return {
      isLoad: false,
			bookList: [],
      pagination: initPagination()
    }
  },
  created () {
    this.getBookPageList()
  },
	methods: {
    textEllipsis,
    scaleImageWidthInCOS,
    getBookPageList () {
      const { queryParams, pagination } = this
      const { pageNum, pageSize } = pagination
      const { subType, keyword } = queryParams
      return getBookPageList({
        type: subType || null,
        keyword: keyword || '',
        pageNum,
        pageSize
      })
        .then(data => {
					const list = _get(data, 'content') || []
          if (list.length < pageSize) {
            pagination.isLast = true
          }
          this.bookList = this.bookList.concat(list)
        })
        .finally(() => {
          this.isLoad = true
        })
    },
    refreshList () {
			this.isLoad = false
      this.bookList = []
      this.pagination = initPagination()
      this.getBookPageList()
    },
		onClickCard (item) {
			if (item) {
				uni.navigateTo({
					url: `/pages/book/detail?id=${encodeURIComponent(item.id)}`
				});
			}
		},
    onScrollToLower () {
      const { pagination } = this
      console.log('onScrollToLower')
      if (!pagination.isLast) {
        pagination.pageNum ++
        this.getBookPageList()
      }
    }
	}
}
</script>
<style lang="less">
@import './index.less';
</style>
