// react-native-expo/src/pages/login/password.tsx
import { styles } from './password.styles';
import { type ComponentProps, useMemo, useState } from 'react';
import { Alert, Image, Pressable, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { api } from '@/lib/api';

const banner = 'https://assets.izhao.com.cn/images/fantasy-illustration-7600566_1280.jpg';

export default function PasswordScreen() {
  const [password, setPassword] = useState('');
  const [newPassword, setNewPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const valid = useMemo(() => Boolean(password) && /^.{6,12}$/.test(newPassword) && confirmPassword === newPassword, [confirmPassword, newPassword, password]);

  const updatePassword = () => {
    if (!valid || submitting) {
      const message = !password ? '请输入旧密码' : !/^.{6,12}$/.test(newPassword) ? '新密码不能少于6位' : '两次输入的新密码不一致';
      Alert.alert('提示', message);
      return;
    }
    setSubmitting(true);
    api.updatePassword(password, newPassword).then(() => {
      Alert.alert('提示', '密码修改成功！', [{ text: '确定', onPress: () => router.replace('/login') }]);
    }).catch(error => Alert.alert('提示', error instanceof Error ? error.message : '密码修改失败')).finally(() => setSubmitting(false));
  };

  return <View style={styles.page}>
    <Image source={{ uri: banner }} style={styles.banner} />
    <View style={styles.form}>
      <Field label="旧密码" value={password} onChangeText={setPassword} placeholder="请输入旧密码" />
      <Field label="新密码" value={newPassword} onChangeText={setNewPassword} placeholder="请输入新密码" />
      <Field label="确认新密码" value={confirmPassword} onChangeText={setConfirmPassword} placeholder="请再次输入新密码" />
    </View>
    <View style={styles.submit}><Pressable onPress={updatePassword} style={[styles.button, (!valid || submitting) && styles.disabled]}><Text style={styles.buttonText}>{submitting ? '提交中…' : '提交'}</Text></Pressable></View>
  </View>;
}

function Field({ label, ...props }: { label: string } & ComponentProps<typeof TextInput>) {
  return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput {...props} secureTextEntry style={styles.input} placeholderTextColor="#b3b3b3" maxLength={12} /></View>;
}

// uni-vite/src/pages/login/password.vue
 <template>
  <view class="password_page">
    <image
      class="banner"
      :src="scaleImageWidthInCOS('https://yizhao-1259410276.cos.ap-shanghai.myqcloud.com/images/fantasy-illustration-7600566_1280.jpg')"
      mode="widthFix"
    />
    <view class="form">
      <uni-forms
        ref="Form"
        :modelValue="formValues"
        :label-width="100"
        :border="true"
        :rules="rules"
        validateTrigger="bind"
      >
        <uni-forms-item label="旧密码" name="password" required>
          <uni-easyinput
            v-model="formValues.password"
            type="password"
            placeholder="请输入旧密码"
            :maxlength="12"
            @blur="onChange"
          />
        </uni-forms-item>
        <uni-forms-item label="新密码" name="newPassword" required>
          <uni-easyinput
            v-model="formValues.newPassword"
            type="password"
            placeholder="请输入新密码"
            :maxlength="12"
            @blur="onChange"
          />
        </uni-forms-item>
        <uni-forms-item label="确认新密码" name="confirmPassword" required>
          <uni-easyinput
            v-model="formValues.confirmPassword"
            type="password"
            placeholder="请再次输入新密码"
            :maxlength="12"
            @blur="onChange"
          />
        </uni-forms-item>
      </uni-forms>
    </view>
    <view class="submit">
      <view :class="['button', isDisabled ? 'disabled' : '']" @click="updatePassword">
        提交
      </view>
    </view>
  </view>
</template>

<script>
import { get as _get } from 'lodash'
import { scaleImageWidthInCOS } from '@/utils/common'
import { updatePassword } from '@/api'

export default {
  data() {
    return {
      isDisabled: true,
      formValues: {
        password: '',
        newPassword: '',
        confirmPassword: ''
      },
      rules: {
        password: {
          rules: [
            { required: true, errorMessage: '请输入旧密码', trigger: ['blur', 'change'] },
          ]
        },
        newPassword: {
          rules: [
            { required: true, errorMessage: '请输入新密码', trigger: ['blur', 'change'] },
            { pattern: '^.{6,12}$', errorMessage: '新密码不能少于6位', trigger: ['blur', 'change'] }
          ]
        },
        confirmPassword: {
          rules: [
            { required: true, errorMessage: '请确认新密码', trigger: ['blur', 'change'] },
            {
              validateFunction : (rule, value, data, callback) => {
                if (value !== data.newPassword) {
                  return callback(rule.errorMessage);
                }
                return true
              },
              errorMessage: '两次输入的新密码不一致',
              trigger: ['blur', 'change'],
            }
          ]
        }
      }
    }
  },
  methods: {
    scaleImageWidthInCOS,
    onChange() {
      setTimeout(() => {
        this.$refs.Form.validate()
          .then(() => {
            this.isDisabled = false
          })
          .catch(() => {
            this.isDisabled = true
          })
      }, 100)
    },
    updatePassword() {
      const { $refs, formValues } = this
      const { password, newPassword } = formValues
      $refs.Form.validate().then(res => {
        return updatePassword({
          password,
          newPassword
        }).then((data) => {
          uni.showToast({
            title: '密码修改成功！',
            icon: 'success'
          });
          setTimeout(() => {
            uni.redirectTo({
              url: '/pages/login/index'
            });
          }, 1000);
        })
      }).catch((e) => {
        const errorMessage = _get(e, 'errMsg') || _get(e, '[0].errorMessage') || '请完善表单信息！'
        uni.showToast({
          title: errorMessage,
          icon: 'none'
        })
      })
    }
  }
}
</script>

<style lang="less">
  @import './password.less';
</style>
